---
name: "Updatecli"

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every hour
    - cron: '0 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Apply
        run: "updatecli apply --config .github/updatecli/updatecli.d --values .github/updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
